### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'views'

### ISSUE THREAD

**Issue by evandrocoan** [aziz/SublimeANSI#43]
This showed up when Sublime Text started:
```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\ANSIescape\ansi.py", line 237, in check_left_ansi
    if not self._is_view_valid(view):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\ANSIescape\ansi.py", line 271, in _is_view_valid
    if view not in view.window().views():
AttributeError: 'NoneType' object has no attribute 'views'
```
This seems to coincides with the `Overrides Reports` package report.

___

Related:

1. https://github.com/aziz/SublimeANSI/issues/12 event listener callback error

**Comment by giampaolo** [comment]
Despite this is an old issue, it is still valid today. I cannot tell how to reproduce it, but I experience it kind of regularly (say once per week):

```
Traceback (most recent call last):
  File "/home/giampaolo/.config/sublime-text/Installed Packages/ANSIescape.sublime-package/ansi.py", line 343, in check_left_ansi
    if not self._is_view_valid(view):
  File "/home/giampaolo/.config/sublime-text/Installed Packages/ANSIescape.sublime-package/ansi.py", line 377, in _is_view_valid
    if view not in view.window().views():
AttributeError: 'NoneType' object has no attribute 'views'
```

It appears like a simple race condition: `view.window()` exists at line 373 but disappears at 377:
https://github.com/aziz/SublimeANSI/blob/c8f45de5e8c7a43f01d08b4a22824f68700ff08b/ansi.py#L372-L379
The bugfix appears simple: save the `view.window()` object in a variable at the beginning of the function. AFAICT the solution proposed in https://github.com/aziz/SublimeANSI/pull/48 appears correct. Is it possible to merge that or a variant of it?
